### ISSUE TITLE
Invalid profile link

### ISSUE THREAD

**Issue by Holoti** [Laynexx-ns/laynexx.github.io#1]
@laynexx_bezdar is non-existent Telegram user
https://github.com/Laynexx-ns/laynexx.github.io/blob/bacc8393fdc56f8b1619b20399e6038da6cc18c6/src/Links/MyLinks.tsx#L17-L20

**Comment by Laynexx-ns** [comment]
этот проект мертв))

Я знаю, что там мой старый тг юзернейм, я буду вообще его полностью переделывать по многим причинам, когда будет время. Сейчас даже ссылка на его хост нигде не размещена
